CREATE TABLE LOG_MIN tablespace calisma_tbs COMPRESS FOR QUERY LOW PARALLEL 8 as
select 
1 AS LOG,
TO_CHAR(timestamp '2023-09-01 14:00:00' + numtodsinterval(rownum*1,'MINUTE'),'YYYYMMDDHH24MI') AS TIMESTAMP
from dual
connect by level <= 1000000;


CREATE TABLE INTERVAL_MINUTES tablespace calisma_tbs COMPRESS FOR QUERY LOW PARALLEL 8 as
SELECT TIME_INT,SUM(LOG) AS TALEP
FROM (select LOG,
        CASE WHEN TO_NUMBER(TO_CHAR(TO_DATE(TIMESTAMP,'YYYYMMDDHH24MI'),'MI'))>=0 AND TO_NUMBER(TO_CHAR(TO_DATE(TIMESTAMP,'YYYYMMDDHH24MI'),'MI')) <15 THEN TO_NUMBER(TO_CHAR(TO_DATE(TIMESTAMP,'YYYYMMDDHH24MI')+1/96,'YYYYMMDDHH24')||'15') 
        WHEN TO_NUMBER(TO_CHAR(TO_DATE(TIMESTAMP,'YYYYMMDDHH24MI'),'MI'))>=15 AND TO_NUMBER(TO_CHAR(TO_DATE(TIMESTAMP,'YYYYMMDDHH24MI'),'MI')) <30 THEN TO_NUMBER(TO_CHAR(TO_DATE(TIMESTAMP,'YYYYMMDDHH24MI')+1/96,'YYYYMMDDHH24')||'30') 
        WHEN TO_NUMBER(TO_CHAR(TO_DATE(TIMESTAMP,'YYYYMMDDHH24MI'),'MI'))>=30 AND TO_NUMBER(TO_CHAR(TO_DATE(TIMESTAMP,'YYYYMMDDHH24MI'),'MI')) <45 THEN TO_NUMBER(TO_CHAR(TO_DATE(TIMESTAMP,'YYYYMMDDHH24MI')+1/96,'YYYYMMDDHH24')||'45') 
        WHEN TO_NUMBER(TO_CHAR(TO_DATE(TIMESTAMP,'YYYYMMDDHH24MI'),'MI'))>=45 AND TO_NUMBER(TO_CHAR(TO_DATE(TIMESTAMP,'YYYYMMDDHH24MI'),'MI')) <=59 THEN TO_NUMBER(TO_CHAR(TO_DATE(TIMESTAMP,'YYYYMMDDHH24MI')+1/96,'YYYYMMDDHH24')||'00') END TIME_INT,
        TO_NUMBER(TO_CHAR(TO_DATE(TIMESTAMP,'YYYYMMDDHH24MI'),'YYYYMMDDHH24MI')) 
        from LOG_MIN)
GROUP BY TIME_INT 
ORDER BY 1 DESC;